### GET ORNEGI
GET https://jsonplaceholder.typicode.com/posts/1

### POST ORNEGI
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "Servis islemleri",
  "body": "Rest Client kullanarak VsCode uzerinden servis cagrisi",
  "userId": 1
}